# Generated by Django 5.2 on 2026-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("user", "User"),
                    ("bank_admin", "Bank Admin"),
                ],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
