# Generated by Django 5.2 on 2026-05-19 07:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialInstitution",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "momo_number",
                    models.CharField(
                        help_text="Phone number where users send savings (MTN/Orange MoMo)",
                        max_length=30,
                        verbose_name="Mobile Money Number",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Financial Institution",
                "verbose_name_plural": "Financial Institutions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food & Groceries"),
                            ("transport", "Transport"),
                            ("bills", "Utilities & Bills"),
                            ("entertainment", "Entertainment"),
                            ("health", "Health"),
                            ("education", "Education"),
                            ("savings", "Savings"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Expense Date"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "expense_date"],
                        name="finance_exp_user_id_b6bcca_idx",
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="finance_exp_user_id_2a29e1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DepositTransaction",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "momo_transaction_id",
                    models.CharField(
                        help_text="Transaction ID from user's Mobile Money app",
                        max_length=100,
                        verbose_name="MoMo Transaction ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Requested At"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Confirmed At"
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_deposits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmed By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="finance.financialinstitution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deposit Transaction",
                "verbose_name_plural": "Deposit Transactions",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "institution"],
                        name="finance_dep_status_7dd5ca_idx",
                    ),
                    models.Index(
                        fields=["user", "-requested_at"],
                        name="finance_dep_user_id_13c6b1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInstitutionAccount",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional account number assigned by the institution",
                        max_length=100,
                        verbose_name="Account Number",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accounts",
                        to="finance.financialinstitution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Institution Account",
                "verbose_name_plural": "User Institution Accounts",
                "unique_together": {("user", "institution")},
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_payout_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when institution will send MoMo",
                        null=True,
                        verbose_name="Scheduled Payout Date",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="finance.financialinstitution",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Processed By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Withdrawal Request",
                "verbose_name_plural": "Withdrawal Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "institution"],
                        name="finance_wit_status_89e67a_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="finance_wit_user_id_f2f188_idx",
                    ),
                ],
            },
        ),
    ]
